#! /bin/sh

# Test recognition of Python brace format strings.

tmpfiles=""
trap 'rm -fr $tmpfiles' 1 2 3 15

tmpfiles="$tmpfiles f-pyb-1.data"
cat <<\EOF > f-pyb-1.data
# Invalid: no argument
"abc"
# Valid: a named argument
"abc{value}"
# Valid: a number argument
"abc{0}"
# Invalid: an empty name
"abc{}"
# Invalid: unterminated name
"abc{value"
# Valid: three arguments, two with equal names
"abc{addr},{char},{addr}"
# Invalid: place-holder contains a space.
"{foo bar}"
# Invalid: missing right angle bracket.
"{foo bar"
# Invalid: percent sign not allowed.
"{foo%bar}"
EOF

: ${XGETTEXT=xgettext}
n=0
while read comment; do
  read string
  n=`expr $n + 1`
  tmpfiles="$tmpfiles f-pyb-1-$n.in f-pyb-1-$n.po"
  cat <<EOF > f-pyb-1-$n.in
gettext(${string});
EOF
  ${XGETTEXT} -L Python -o f-pyb-1-$n.po f-pyb-1-$n.in || exit 1
  test -f f-pyb-1-$n.po || exit 1
  fail=
  if echo "$comment" | grep 'Valid:' > /dev/null; then
    if grep python-brace-format f-pyb-1-$n.po > /dev/null; then
      :
    else
      fail=yes
    fi
  else
    if grep python-brace-format f-pyb-1-$n.po > /dev/null; then
      fail=yes
    else
      :
    fi
  fi
  if test -n "$fail"; then
    echo "Format string recognition error:" 1>&2
    cat f-pyb-1-$n.in 1>&2
    echo "Got:" 1>&2
    cat f-pyb-1-$n.po 1>&2
    exit 1
  fi
  rm -f f-pyb-1-$n.in f-pyb-1-$n.po
done < f-pyb-1.data

rm -fr $tmpfiles

exit 0
